// M39.1 -- the numbers a hole is drilled to.
//
// A table of published values fails INVISIBLY. Nothing crashes, no test goes
// red on its own, and the drawing is perfectly legible: it just says a
// diameter no standard backs, and the part comes back from the shop wrong.
//
// So the shape of these tests is deliberate: NAMED SPOT-CHECKS against values
// a machinist would recognise, and a refusal wherever the table has no answer.
// A test that only checked "some number came back" would pass against a table
// of zeros.

#include "Core/Feature/HoleStandards.h"

#include <gtest/gtest.h>

#include <cmath>
#include <string>

namespace {

using namespace paramcad;

TEST(HoleStandardsTest, M39_TAP_001_TheDrillForTheCommonThreadsIsWhatTheStandardSays) {
    // Read off a tap chart, size by size. If these are ever generated by the
    // same formula the code uses, this test stops being evidence of anything.
    struct Known {
        double nominal;
        double pitch;
        double drill;
    };
    const Known chart[] = {
        {3.0, 0.5, 2.5},   {4.0, 0.7, 3.3},   {5.0, 0.8, 4.2},
        {6.0, 1.0, 5.0},   {8.0, 1.25, 6.8},  {10.0, 1.5, 8.5},
        {12.0, 1.75, 10.2}, {16.0, 2.0, 14.0}, {20.0, 2.5, 17.5},
    };
    for (const Known& one : chart) {
        const auto thread = MetricCoarseThreadOfSize(one.nominal);
        ASSERT_TRUE(thread.has_value()) << "M" << one.nominal << " is not in the table";
        EXPECT_NEAR(thread->pitchMm, one.pitch, 1e-9) << "M" << one.nominal;
        EXPECT_NEAR(thread->tapDrillMm, one.drill, 1e-9) << "M" << one.nominal;
    }
}

TEST(HoleStandardsTest, M39_TAP_002_TheFORMULAIsWrongOnTheTwoCommonestThreads) {
    // THIS IS THE WHOLE ARGUMENT FOR A TABLE.
    //
    // "Tap drill = nominal minus pitch" is right for seventeen of the nineteen
    // sizes and wrong for M8 and M12 -- the two threads that turn up on more
    // parts than all the others together. A build that quietly switched to the
    // formula would pass every other check in this file.
    const auto m8 = MetricCoarseThreadOfSize(8.0);
    ASSERT_TRUE(m8.has_value());
    EXPECT_NEAR(m8->tapDrillMm, 6.8, 1e-9);
    EXPECT_NE(m8->tapDrillMm, 8.0 - 1.25) << "the formula answered instead of the table";

    const auto m12 = MetricCoarseThreadOfSize(12.0);
    ASSERT_TRUE(m12.has_value());
    EXPECT_NEAR(m12->tapDrillMm, 10.2, 1e-9);
    EXPECT_NE(m12->tapDrillMm, 12.0 - 1.75) << "the formula answered instead of the table";

    // ...and where the formula IS right, the table agrees with it. Said out
    // loud so the two above read as exceptions rather than as typing errors.
    const auto m10 = MetricCoarseThreadOfSize(10.0);
    ASSERT_TRUE(m10.has_value());
    EXPECT_NEAR(m10->tapDrillMm, 10.0 - 1.5, 1e-9);
}

TEST(HoleStandardsTest, M39_TAP_003_ASizeTheTableDoesNotHoldIsREFUSED) {
    // Interpolating would print a manufacturing instruction this program made
    // up. There is no M9 and no M7 in ISO 261's first choice, and a hole that
    // claims one is a hole nobody can make.
    EXPECT_FALSE(MetricCoarseThreadOfSize(9.0).has_value());
    EXPECT_FALSE(MetricCoarseThreadOfSize(7.0).has_value());
    EXPECT_FALSE(MetricCoarseThreadOfSize(0.0).has_value());
    EXPECT_FALSE(MetricCoarseThreadOfSize(-8.0).has_value());
    EXPECT_FALSE(MetricCoarseThreadOfSize(500.0).has_value());
}

TEST(HoleStandardsTest, M39_TAP_004_ADesignationIsReadAndAFINEPitchIsREFUSED) {
    // "M8" and "M8x1.25" are the same hole. "M8x1" is NOT: it is a fine
    // thread, drilled 7.0, and answering it with the coarse thread's 6.8 would
    // be the worst of the three available outcomes -- a confident wrong number
    // rather than a refusal.
    const auto plain = MetricCoarseThread("M8");
    ASSERT_TRUE(plain.has_value());
    EXPECT_NEAR(plain->tapDrillMm, 6.8, 1e-9);

    const auto spelled = MetricCoarseThread("M8x1.25");
    ASSERT_TRUE(spelled.has_value());
    EXPECT_NEAR(spelled->tapDrillMm, 6.8, 1e-9);
    EXPECT_EQ(spelled->designation(), "M8x1.25");

    EXPECT_FALSE(MetricCoarseThread("M8x1").has_value()) << "a fine pitch was read as coarse";
    EXPECT_FALSE(MetricCoarseThread("M12x1.5").has_value());

    // Ordinary slop in what a user types is fine; nonsense is not.
    EXPECT_TRUE(MetricCoarseThread(" m8 ").has_value());
    EXPECT_TRUE(MetricCoarseThread("M8X1.25").has_value());
    EXPECT_FALSE(MetricCoarseThread("").has_value());
    EXPECT_FALSE(MetricCoarseThread("8").has_value());
    EXPECT_FALSE(MetricCoarseThread("Mx1.25").has_value());
    EXPECT_FALSE(MetricCoarseThread("M8-6H").has_value())
        << "a tolerance class is not a pitch, and reading it as one would answer wrongly";
    EXPECT_FALSE(MetricCoarseThread("M8 nonsense").has_value());
}

TEST(HoleStandardsTest, M39_TAP_005_TheDesignationARoundTripGivesBackIsTheOneADrawingWrites) {
    // "M6x1", not "M6x1.000000" -- the designation goes on the drawing, and a
    // trailing zero parade is how a reader knows a program wrote it.
    EXPECT_EQ(MetricCoarseThreadOfSize(6.0)->designation(), "M6x1");
    EXPECT_EQ(MetricCoarseThreadOfSize(2.5)->designation(), "M2.5x0.45");
    EXPECT_EQ(MetricCoarseThreadOfSize(12.0)->designation(), "M12x1.75");
    // ...and what it writes, it reads back.
    const std::string written = MetricCoarseThreadOfSize(12.0)->designation();
    ASSERT_TRUE(MetricCoarseThread(written).has_value());
    EXPECT_NEAR(MetricCoarseThread(written)->tapDrillMm, 10.2, 1e-9);
}

TEST(HoleStandardsTest, M39_CLEAR_001_TheThreeClearanceSeriesAreDIFFERENTAndPublished) {
    // The difference is the point: a plate of M6 holes at the close fit will
    // not go on unless everything else was made perfectly, and one at the
    // loose fit rattles. A build where all three returned the same number
    // would look entirely healthy.
    EXPECT_NEAR(*ClearanceHoleMm(6.0, ClearanceFit::Close), 6.4, 1e-9);
    EXPECT_NEAR(*ClearanceHoleMm(6.0, ClearanceFit::Normal), 6.6, 1e-9);
    EXPECT_NEAR(*ClearanceHoleMm(6.0, ClearanceFit::Loose), 7.0, 1e-9);

    EXPECT_NEAR(*ClearanceHoleMm(8.0, ClearanceFit::Close), 8.4, 1e-9);
    EXPECT_NEAR(*ClearanceHoleMm(8.0, ClearanceFit::Normal), 9.0, 1e-9);
    EXPECT_NEAR(*ClearanceHoleMm(8.0, ClearanceFit::Loose), 10.0, 1e-9);

    EXPECT_NEAR(*ClearanceHoleMm(3.0, ClearanceFit::Normal), 3.4, 1e-9);
    EXPECT_NEAR(*ClearanceHoleMm(12.0, ClearanceFit::Normal), 13.5, 1e-9);

    // A CLEARANCE HOLE IS ALWAYS BIGGER THAN THE SCREW, and the series always
    // run the same way round. Getting them swapped is a defect that reads as
    // a perfectly sensible number.
    for (const double size : {3.0, 4.0, 5.0, 6.0, 8.0, 10.0, 12.0, 16.0, 20.0}) {
        const double close = *ClearanceHoleMm(size, ClearanceFit::Close);
        const double normal = *ClearanceHoleMm(size, ClearanceFit::Normal);
        const double loose = *ClearanceHoleMm(size, ClearanceFit::Loose);
        EXPECT_GT(close, size) << "M" << size << " close fit would not pass its own screw";
        EXPECT_LT(close, normal) << "M" << size;
        EXPECT_LT(normal, loose) << "M" << size;
    }
    EXPECT_FALSE(ClearanceHoleMm(9.0, ClearanceFit::Normal).has_value());
}

TEST(HoleStandardsTest, M39_CBORE_001_ACounterboreTakesTheHeadAndFinishesFLUSH) {
    const auto m6 = CounterboreForSocketHead(6.0);
    ASSERT_TRUE(m6.has_value());
    EXPECT_NEAR(m6->diameterMm, 11.0, 1e-9);
    // The depth is the head height: deeper and the head is below the surface
    // where a key cannot reach it, shallower and it stands proud.
    EXPECT_NEAR(m6->depthMm, 6.0, 1e-9);

    EXPECT_NEAR(CounterboreForSocketHead(8.0)->diameterMm, 15.0, 1e-9);
    EXPECT_NEAR(CounterboreForSocketHead(10.0)->diameterMm, 18.0, 1e-9);
    EXPECT_NEAR(CounterboreForSocketHead(3.0)->diameterMm, 6.5, 1e-9);

    // THE RECESS HAS TO SWALLOW THE CLEARANCE HOLE, or the counterbore is
    // narrower than the hole through it -- which is not a shape.
    for (const double size : {3.0, 4.0, 5.0, 6.0, 8.0, 10.0, 12.0, 16.0, 20.0}) {
        const auto bore = CounterboreForSocketHead(size);
        ASSERT_TRUE(bore.has_value()) << "M" << size;
        EXPECT_GT(bore->diameterMm, *ClearanceHoleMm(size, ClearanceFit::Loose)) << "M" << size;
    }

    // No standard socket head counterbore is published here for M1.6, so none
    // is invented.
    EXPECT_FALSE(CounterboreForSocketHead(1.6).has_value());
    EXPECT_FALSE(CounterboreForSocketHead(9.0).has_value());
}

TEST(HoleStandardsTest, M39_CSK_001_ACountersinkCarriesItsANGLEAndNotJustADiameter) {
    // 90 degrees is the metric standard. An 82 degree screw -- the imperial
    // one -- in a 90 degree hole stands proud by a hair, which is enough to
    // stop two faces meeting, and the drawing looks right either way. So the
    // angle is part of the answer rather than an assumption downstream.
    const auto m6 = CountersinkForFlatHead(6.0);
    ASSERT_TRUE(m6.has_value());
    EXPECT_NEAR(m6->diameterMm, 12.0, 1e-9);
    EXPECT_NEAR(m6->includedAngleDeg, 90.0, 1e-9);

    EXPECT_NEAR(CountersinkForFlatHead(4.0)->diameterMm, 8.0, 1e-9);
    EXPECT_NEAR(CountersinkForFlatHead(8.0)->diameterMm, 16.0, 1e-9);

    for (const double size : {3.0, 4.0, 5.0, 6.0, 8.0, 10.0}) {
        const auto cone = CountersinkForFlatHead(size);
        ASSERT_TRUE(cone.has_value()) << "M" << size;
        EXPECT_GT(cone->diameterMm, *ClearanceHoleMm(size, ClearanceFit::Loose)) << "M" << size;
        EXPECT_NEAR(cone->includedAngleDeg, 90.0, 1e-9) << "M" << size;
    }

    EXPECT_FALSE(CountersinkForFlatHead(12.0).has_value())
        << "a size with no published flat head here was answered anyway";
}

TEST(HoleStandardsTest, M39_TABLE_001_EverySizeAnswersEveryQuestionItClaimsTo) {
    // The rows are one table on purpose. Split into four -- pitches, drills,
    // clearances, counterbores -- they would be kept in step by hand, and a
    // size present in one and missing from another is exactly the shape of
    // defect this project keeps closing. This walks the sizes that a thread
    // knows about and insists the clearance table knows them too.
    for (const double size : {1.6, 2.0, 2.5, 3.0, 4.0, 5.0, 6.0, 8.0, 10.0, 12.0, 14.0, 16.0,
                              18.0, 20.0, 22.0, 24.0, 27.0, 30.0, 36.0}) {
        ASSERT_TRUE(MetricCoarseThreadOfSize(size).has_value()) << "M" << size;
        EXPECT_TRUE(ClearanceHoleMm(size, ClearanceFit::Normal).has_value()) << "M" << size;
        // A TAP DRILL IS SMALLER THAN THE THREAD and a clearance hole bigger.
        // Swap the two columns and every number is still plausible.
        EXPECT_LT(MetricCoarseThreadOfSize(size)->tapDrillMm, size) << "M" << size;
        EXPECT_GT(*ClearanceHoleMm(size, ClearanceFit::Normal), size) << "M" << size;
    }
}

// The symbols a callout is built from, so a test never has to hold a raw
// escape next to a digit.
const std::string kDia = "\xE2\x8C\x80";
const std::string kCbore = "\xE2\x8C\xB4";
const std::string kCsink = "\xE2\x8C\xB5";
const std::string kDeep = "\xE2\x96\xBC";

bool Says(const HoleSizes& sizes, const std::string& fragment) {
    return sizes.callout.find(fragment) != std::string::npos;
}

TEST(HoleStandardsTest, M39_SIZE_001_ATappedHoleIsDrilledToTheTAPDrillAndCalledOutByItsTHREAD) {
    // THE ONE THAT MATTERS MOST. Drill an M8 hole to 8 and the tap has nothing
    // to bite; the part is scrap and the screen showed a perfectly round hole
    // at a diameter nobody looks at twice.
    HoleScrew screw;
    screw.designation = "M8";
    screw.tapped = true;

    const HoleSizes sizes = SizeAHole(screw, HoleKind::Simple, 0.0, 0.0);
    ASSERT_TRUE(sizes.ok) << sizes.why;
    EXPECT_NEAR(sizes.drillDiameterMm, 6.8, 1e-9) << "an M8 hole was drilled to its thread size";

    // A tapped hole is called out by its THREAD, not by the drill: 6.8 on the
    // drawing tells the shop to leave it untapped.
    EXPECT_TRUE(Says(sizes, "M8x1.25")) << sizes.callout;
    EXPECT_TRUE(Says(sizes, "THRU")) << sizes.callout;
    EXPECT_FALSE(Says(sizes, "6.8")) << sizes.callout;
}

TEST(HoleStandardsTest, M39_SIZE_002_AClearanceHoleIsDrilledToTheFITThatWasAskedFor) {
    HoleScrew screw;
    screw.designation = "M8";
    screw.tapped = false;

    screw.fit = ClearanceFit::Normal;
    const HoleSizes normal = SizeAHole(screw, HoleKind::Simple, 0.0, 0.0);
    ASSERT_TRUE(normal.ok) << normal.why;
    EXPECT_NEAR(normal.drillDiameterMm, 9.0, 1e-9);
    EXPECT_EQ(normal.callout, kDia + "9 THRU");

    screw.fit = ClearanceFit::Close;
    const HoleSizes close = SizeAHole(screw, HoleKind::Simple, 0.0, 0.0);
    ASSERT_TRUE(close.ok) << close.why;
    EXPECT_NEAR(close.drillDiameterMm, 8.4, 1e-9)
        << "the fit that was asked for was not the one that was drilled";
    EXPECT_EQ(close.callout, kDia + "8.4 THRU");
}

TEST(HoleStandardsTest, M39_SIZE_003_TheCALLOUTAndTheDRILLAreOneAnswer) {
    // They are computed together on purpose: a drawing that says one diameter
    // over a hole cut to another is worse than either mistake alone, because
    // it is a correct-looking instruction to make the wrong part. This asserts
    // the number the drawing prints IS the number the tool is sized to.
    HoleScrew screw;
    screw.designation = "M10";
    for (const ClearanceFit fit :
         {ClearanceFit::Close, ClearanceFit::Normal, ClearanceFit::Loose}) {
        screw.fit = fit;
        const HoleSizes sizes = SizeAHole(screw, HoleKind::Simple, 0.0, 0.0);
        ASSERT_TRUE(sizes.ok) << sizes.why;
        const std::string printed = sizes.callout.substr(
            kDia.size(), sizes.callout.find(' ') - kDia.size());
        EXPECT_NEAR(std::stod(printed), sizes.drillDiameterMm, 1e-9)
            << "the callout says " << printed << " over a hole cut to "
            << sizes.drillDiameterMm;
    }
}

TEST(HoleStandardsTest, M39_SIZE_004_ADepthIsSaidAsADepthAndATHROUGHHoleSaysTHRU) {
    // "THRU" is a word, not a big number. A through hole whose callout carries
    // a depth is one a machinist drills to that depth and stops -- and the
    // part looks finished.
    HoleScrew none;
    const HoleSizes through = SizeAHole(none, HoleKind::Simple, 12.0, 0.0);
    ASSERT_TRUE(through.ok) << through.why;
    EXPECT_EQ(through.callout, kDia + "12 THRU");

    const HoleSizes blind = SizeAHole(none, HoleKind::Simple, 12.0, 20.0);
    ASSERT_TRUE(blind.ok) << blind.why;
    EXPECT_EQ(blind.callout, kDia + "12 " + kDeep + " 20");
    EXPECT_FALSE(Says(blind, "THRU")) << blind.callout;
}

TEST(HoleStandardsTest, M39_SIZE_005_ACounterboreCarriesItsOwnDiameterAndDepth) {
    HoleScrew screw;
    screw.designation = "M8";
    const HoleSizes sizes = SizeAHole(screw, HoleKind::Counterbore, 0.0, 0.0);
    ASSERT_TRUE(sizes.ok) << sizes.why;

    EXPECT_NEAR(sizes.drillDiameterMm, 9.0, 1e-9) << "the screw still has to pass through";
    EXPECT_NEAR(sizes.counterboreDiameterMm, 15.0, 1e-9);
    EXPECT_NEAR(sizes.counterboreDepthMm, 8.0, 1e-9);
    EXPECT_EQ(sizes.callout, kDia + "9 THRU  " + kCbore + " " + kDia + "15 " + kDeep + " 8");
    // ...and nothing about a countersink got filled in as well.
    EXPECT_EQ(sizes.countersinkDiameterMm, 0.0);
}

TEST(HoleStandardsTest, M39_SIZE_006_ACountersinkCarriesItsANGLE) {
    HoleScrew screw;
    screw.designation = "M6";
    const HoleSizes sizes = SizeAHole(screw, HoleKind::Countersink, 0.0, 0.0);
    ASSERT_TRUE(sizes.ok) << sizes.why;
    EXPECT_NEAR(sizes.drillDiameterMm, 6.6, 1e-9);
    EXPECT_NEAR(sizes.countersinkDiameterMm, 12.0, 1e-9);
    EXPECT_NEAR(sizes.countersinkAngleDeg, 90.0, 1e-9);
    EXPECT_TRUE(Says(sizes, kCsink)) << sizes.callout;
    EXPECT_TRUE(Says(sizes, "90")) << sizes.callout;
    EXPECT_EQ(sizes.counterboreDiameterMm, 0.0);
}

TEST(HoleStandardsTest, M39_SIZE_007_AThreadTheTableDoesNotHoldIsREFUSEDNotFallenBackOn) {
    // THE FALLBACK IS THE DEFECT. Given an unreadable designation, taking the
    // typed diameter instead drills a hole that is the wrong size, looks
    // entirely right, and gets a callout naming a thread it cannot take.
    HoleScrew screw;
    screw.designation = "M9";
    screw.tapped = true;

    const HoleSizes sizes = SizeAHole(screw, HoleKind::Simple, 12.0, 0.0);
    EXPECT_FALSE(sizes.ok) << "an unknown thread was answered with the typed diameter";
    EXPECT_NE(sizes.drillDiameterMm, 12.0);
    EXPECT_FALSE(sizes.why.empty());
    EXPECT_NE(sizes.why.find("M9"), std::string::npos) << sizes.why;

    // A fine pitch lands the same way, for the same reason: its drill is not
    // in this table and the coarse one would be a confident wrong number.
    HoleScrew fine;
    fine.designation = "M8x1";
    fine.tapped = true;
    EXPECT_FALSE(SizeAHole(fine, HoleKind::Simple, 12.0, 0.0).ok);
}

TEST(HoleStandardsTest, M39_SIZE_008_ARecessNeedsToKnowWHICHScrewItIsFor) {
    // There is no such thing as the standard counterbore for a 12.7 mm hole:
    // a recess is sized for a screw HEAD. Asked for on a hole that names no
    // screw, the honest answer is a refusal.
    HoleScrew none;
    const HoleSizes bored = SizeAHole(none, HoleKind::Counterbore, 12.7, 0.0);
    EXPECT_FALSE(bored.ok);
    EXPECT_NE(bored.why.find("screw"), std::string::npos) << bored.why;

    EXPECT_FALSE(SizeAHole(none, HoleKind::Countersink, 12.7, 0.0).ok);
    // ...but a plain hole at that diameter is a perfectly ordinary thing.
    EXPECT_TRUE(SizeAHole(none, HoleKind::Simple, 12.7, 0.0).ok);

    // A size with no published recess is refused rather than approximated.
    HoleScrew big;
    big.designation = "M12";
    EXPECT_FALSE(SizeAHole(big, HoleKind::Countersink, 0.0, 0.0).ok);
    EXPECT_TRUE(SizeAHole(big, HoleKind::Counterbore, 0.0, 0.0).ok);
}

TEST(HoleStandardsTest, M39_SIZE_009_ACounterboreDeeperThanItsHoleIsREFUSED) {
    // What the kernel would build is a valid solid: a blind pocket with a
    // dimple in the bottom and no hole through it. The callout would still
    // read as a counterbored hole, which is the invisible half of the defect.
    HoleScrew screw;
    screw.designation = "M8"; // counterbore 8 deep
    EXPECT_FALSE(SizeAHole(screw, HoleKind::Counterbore, 0.0, 6.0).ok)
        << "a counterbore deeper than the hole was accepted";
    EXPECT_FALSE(SizeAHole(screw, HoleKind::Counterbore, 0.0, 8.0).ok)
        << "a counterbore exactly as deep as the hole leaves no hole";
    EXPECT_TRUE(SizeAHole(screw, HoleKind::Counterbore, 0.0, 20.0).ok);
    // A THROUGH hole has no depth to be deeper than.
    EXPECT_TRUE(SizeAHole(screw, HoleKind::Counterbore, 0.0, 0.0).ok);
}

TEST(HoleStandardsTest, M39_SIZE_010_APlainHoleStillNeedsAPositiveDiameter) {
    HoleScrew none;
    EXPECT_FALSE(SizeAHole(none, HoleKind::Simple, 0.0, 10.0).ok);
    EXPECT_FALSE(SizeAHole(none, HoleKind::Simple, -5.0, 10.0).ok);
    EXPECT_TRUE(SizeAHole(none, HoleKind::Simple, 0.1, 10.0).ok);
}

} // namespace
